import type { Agent, CallLog, Contact, MockCallLogRow } from "@/types";

export const mockAgents: Agent[] = [
  {
    id: "1",
    name: "Appointment Reminder Bot",
    status: "active",
    voice: "sarah",
    instructions:
      "Call the customer to remind them about their appointment tomorrow. If they confirm, say 'Great, we'll see you then!' If they want to reschedule, ask for a preferred date and time.",
    totalCalls: 342,
    successRate: 94,
    lastActive: "2 min ago",
    createdAt: "2026-06-01",
  },
  {
    id: "2",
    name: "Lead Qualification Agent",
    status: "active",
    voice: "james",
    instructions:
      "Call the lead and ask qualifying questions: what service they need, their budget range, and preferred timeline. If they seem ready to buy, transfer to sales.",
    totalCalls: 156,
    successRate: 87,
    lastActive: "15 min ago",
    createdAt: "2026-06-10",
  },
  {
    id: "3",
    name: "Follow-up Caller",
    status: "paused",
    voice: "emma",
    instructions:
      "Call customers who visited last week. Ask about their experience, if they'd like to schedule another appointment, and note any feedback.",
    totalCalls: 89,
    successRate: 91,
    lastActive: "2 days ago",
    createdAt: "2026-06-15",
  },
  {
    id: "4",
    name: "Order Confirmation Bot",
    status: "active",
    voice: "michael",
    instructions:
      "Confirm the order details with the customer: items ordered, delivery address, and estimated delivery date. Ask if they have any questions.",
    totalCalls: 567,
    successRate: 96,
    lastActive: "5 min ago",
    createdAt: "2026-06-20",
  },
  {
    id: "5",
    name: "Customer Feedback Agent",
    status: "paused",
    voice: "sarah",
    instructions:
      "Thank the customer for their recent visit. Ask them to rate their experience from 1-5 and if they have any suggestions for improvement.",
    totalCalls: 45,
    successRate: 82,
    lastActive: "1 week ago",
    createdAt: "2026-06-25",
  },
];

export const mockContacts: Contact[] = [
  {
    id: "1",
    name: "Maria Garcia",
    phone: "+1 (555) 234-5678",
    email: "maria@email.com",
    dateAdded: "2026-07-01",
  },
  {
    id: "2",
    name: "John Smith",
    phone: "+1 (555) 345-6789",
    email: "john.smith@email.com",
    dateAdded: "2026-07-01",
  },
  {
    id: "3",
    name: "Sarah Johnson",
    phone: "+1 (555) 456-7890",
    email: "sarah.j@email.com",
    dateAdded: "2026-06-28",
  },
  {
    id: "4",
    name: "David Lee",
    phone: "+1 (555) 567-8901",
    email: "david.lee@email.com",
    dateAdded: "2026-06-28",
  },
  {
    id: "5",
    name: "Emma Wilson",
    phone: "+1 (555) 678-9012",
    email: "emma.w@email.com",
    dateAdded: "2026-06-25",
  },
  {
    id: "6",
    name: "Michael Brown",
    phone: "+1 (555) 789-0123",
    email: "m.brown@email.com",
    dateAdded: "2026-06-25",
  },
  {
    id: "7",
    name: "Lisa Anderson",
    phone: "+1 (555) 890-1234",
    email: "lisa.a@email.com",
    dateAdded: "2026-06-22",
  },
  {
    id: "8",
    name: "Robert Taylor",
    phone: "+1 (555) 901-2345",
    email: "r.taylor@email.com",
    dateAdded: "2026-06-20",
  },
  {
    id: "9",
    name: "Jennifer Martinez",
    phone: "+1 (555) 012-3456",
    email: "jen.m@email.com",
    dateAdded: "2026-06-18",
  },
  {
    id: "10",
    name: "William Davis",
    phone: "+1 (555) 123-4567",
    email: "w.davis@email.com",
    dateAdded: "2026-06-15",
  },
];

export const mockCallLogs: CallLog[] = [
  {
    id: "1",
    customerName: "Maria Garcia",
    phone: "+1 (555) 234-5678",
    status: "completed",
    summary:
      "Appointment confirmed for July 8 at 10:00 AM. Patient asked about parking availability.",
    duration: "0:42",
    date: "2026-07-06",
    time: "9:15 AM",
    agentName: "Appointment Reminder Bot",
    crmSynced: true,
  },
  {
    id: "2",
    customerName: "John Smith",
    phone: "+1 (555) 345-6789",
    status: "transferred",
    summary: "Customer wanted to discuss billing discrepancy. Transferred to billing department.",
    duration: "1:15",
    date: "2026-07-06",
    time: "9:08 AM",
    agentName: "Follow-up Caller",
    crmSynced: true,
  },
  {
    id: "3",
    customerName: "Sarah Johnson",
    phone: "+1 (555) 456-7890",
    status: "completed",
    summary:
      "Confirmed oil change for Friday at 3 PM. Also interested in brake inspection special.",
    duration: "0:38",
    date: "2026-07-06",
    time: "8:45 AM",
    agentName: "Appointment Reminder Bot",
    crmSynced: true,
  },
  {
    id: "4",
    customerName: "David Lee",
    phone: "+1 (555) 567-8901",
    status: "missed",
    summary: "No answer after 5 rings. Retry scheduled for tomorrow at 2 PM.",
    duration: "—",
    date: "2026-07-06",
    time: "8:30 AM",
    agentName: "Lead Qualification Agent",
    crmSynced: false,
  },
  {
    id: "5",
    customerName: "Emma Wilson",
    phone: "+1 (555) 678-9012",
    status: "completed",
    summary:
      "Rescheduled haircut from Tuesday to Thursday at 3 PM. Preference for stylist Angela noted.",
    duration: "0:55",
    date: "2026-07-05",
    time: "4:30 PM",
    agentName: "Appointment Reminder Bot",
    crmSynced: true,
  },
  {
    id: "6",
    customerName: "Michael Brown",
    phone: "+1 (555) 789-0123",
    status: "failed",
    summary: "Call failed — invalid phone number. Number appears to be disconnected.",
    duration: "—",
    date: "2026-07-05",
    time: "4:15 PM",
    agentName: "Follow-up Caller",
    crmSynced: false,
  },
];

export const mockLandingCallLogs: readonly MockCallLogRow[] = [
  {
    id: "1",
    customer: "Олена Коваленко",
    time: "09:15",
    status: "Підтверджено",
    statusVariant: "success",
    summary: "Запис підтверджено на 10:00, клієнт запитав про паркування",
    duration: "0:42",
    crm: "Синхронізовано",
  },
  {
    id: "2",
    customer: "Андрій Шевченко",
    time: "09:08",
    status: "Переведено",
    statusVariant: "warning",
    summary: "Клієнт хотів обговорити рахунок. Переведено на менеджера",
    duration: "1:15",
    crm: "Синхронізовано",
  },
  {
    id: "3",
    customer: "Марія Бондаренко",
    time: "08:45",
    status: "Завершено",
    statusVariant: "secondary",
    summary: "Підтвердження замовлення на п'ятницю о 15:00",
    duration: "0:38",
    crm: "Синхронізовано",
  },
  {
    id: "4",
    customer: "Ігор Мельник",
    time: "08:30",
    status: "Пропущено",
    statusVariant: "warning",
    summary: "Немає відповіді після 5 гудків. Повторний дзвінок заплановано",
    duration: "—",
    crm: "Очікує",
  },
] as const;
